# Settings for the in-game Journal
[Journal]
enable_journal = true
show_percentage_in_journal = true
show_message_for_percentage_in_journal = true
show_recent_locations_in_journal = true
show_message_for_most_recent_location_in_journal = true
max_recent_locations_in_journal = 500

# Settings for the on-screen messages
#
# OnScreenMessages refers to the on-screen messages which usually
# appear in the center of the screen, e.g. for when you start a new quest objective.
[OnScreenMessages]
enable_on_screen_messages = false

# Currently, it's all or nothing.
# Only enable_on_screen_messsages works.
#
# The below settings are not used yet (and may never be?)
# They are intended to let you configure which of the messages
# pop up on the screen:
# show_percentage_updates_on_screen = false
# show_message_for_percentage_on_screen = true
# show_message_for_most_recent_location_on_screen = true
# show_recently_discovered_locations_on_screen = false

# Settings for notification messages
#
# Notifications refers to the on-screen messages which usually
# appear in the top left corner of the screen.
[Notifications]
enable_notifications = true
on_location_discovered_notification = true
on_location_discovered_notification_color = "00ffff"
on_location_cleared_notification = true
on_location_cleared_notification_color = "#ff0000"
